# Generated by Django 3.2 on 2024-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activeblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveBlock',
        ),
    ]
