# Generated by Django 3.2 on 2024-10-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_ticket_ticketreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
    ]
