# Generated by Django 3.2 on 2024-09-30 21:01
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('تهران', 'تهران')], max_length=50)),
                ('neighborhood', models.CharField(choices=[('زعفرانیه', 'زعفرانیه'), ('نیاوران', 'نیاوران'), ('قیطریه', 'قیطریه'), ('الهیه', 'الهیه'), ('فرمانیه', 'فرمانیه'), ('ولنجک', 'ولنجک'), ('نازی آباد', 'نازی آباد'), ('پاسداران', 'پاسداران'), ('سعادت آباد', 'سعادت آباد'), ('شهرک غرب', 'شهرک غرب'), ('پونک', 'پونک'), ('جردن (آفریقا)', 'جردن (آفریقا)'), ('میرداماد', 'میرداماد'), ('باغ فردوس', 'باغ فردوس'), ('ونک', 'ونک'), ('جوادیه', 'جوادیه'), ('آجودانیه', 'آجودانیه'), ('یوسف آباد', 'یوسف آباد'), ('تهرانپارس', 'تهرانپارس')], max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('alley', models.CharField(max_length=100)),
                ('block_number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
