# Generated by Django 3.2 on 2024-10-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_activeblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveBlock',
        ),
    ]
